spring:
  application:
    name: Cinema Mate
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_mate
    username: root
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
        show_sql: true







